### ISSUE TITLE
Help with groups_output_stats.txt

### ISSUE THREAD

**Issue by carioka88** [jydu/comap#2]
Hello, 

After running CoMap, I got some files as output: 
- groups_output_null.txt 
- groups_output_stats.txt
- MAP.infos
- MAP.tags.dnd
- MAP.tags.tln

I am trying to understand the output from _groups_output_stats.txt_, I have something like this
```
Group           Size    IsConstant	      Dmax	    Stat          Nmin
[1;109]           2	    no       	    0.599017	   0.400983     2.33283
[69;145]	  2         no              0.357323	   0.64267      2.37528
[69;145;186]	  3	    no              0.52473	   0.47527      2.27338
......
```
What does it mean?
It means that position 1 and 109 from the MSA are coevolving?
Are position 69 and 145 coevolving stronger than  1 and 109? (Because the value _Stat_ is bigger)
The position 69 is coevolving with 145, but not with 186? 

Sorry for all these questions, in the [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2248193/pdf/1471-2148-7-242.pdf) I can see some references to these values (like _Nmin_), but still I am a bit confuse.

Could you help me to better understand these values? 

And also, is there a parameter in CoMap that will look for groups of 2 sites and no more? 

Thank you in advance!

**Comment by jydu** [comment]
Hi,

The two first files are needed to compute p-values for each group, using the R scripts provided with the source package, see for instance https://github.com/jydu/comap/tree/master/examples/simple/ProteinGroupCorrelation .
The CoMapFunctions.R file should not be edited. computePValues.R should be edited to match the input files and set up a few options, including the maximum group sizes. If you are only interested in pairs, however, you might want to run the "pairwise" method (see https://github.com/jydu/comap/tree/master/examples/RNA/BacteriaSSU, also works for Proteins).

The other files are mostly used for visualization (https://github.com/jydu/comap/tree/master/examples/Visualization, still experimental).

Hope this helps! 

Julien.
